/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#006a61",
        "surface-container-highest": "#d9e3f7",
        "on-background": "#121c2a",
        "inverse-on-surface": "#ebf1ff",
        primary: "#000000",
        "surface-dim": "#d0daef",
        "on-primary-fixed-variant": "#404758",
        "surface-container-high": "#dee9fd",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "secondary-container": "#86f2e4",
        "on-tertiary-container": "#858478",
        "on-tertiary-fixed-variant": "#47473d",
        "tertiary-container": "#1c1c14",
        "inverse-surface": "#273140",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#00201d",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#c0c6db",
        "tertiary-fixed": "#e5e3d5",
        "surface-container": "#e6eeff",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-container": "#7d8497",
        "primary-fixed": "#dce2f7",
        "secondary-fixed": "#89f5e7",
        "primary-fixed-dim": "#c0c6db",
        "on-secondary": "#ffffff",
        "primary-container": "#141b2b",
        "on-primary": "#ffffff",
        background: "#f9f9ff",
        "on-tertiary-fixed": "#1c1c14",
        "on-surface": "#121c2a",
        tertiary: "#000000",
        "on-primary-fixed": "#141b2b",
        "on-secondary-container": "#006f66",
        "surface-tint": "#575e70",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005049",
        surface: "#f9f9ff",
        "on-surface-variant": "#45464c",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-variant": "#d9e3f7",
        "tertiary-fixed-dim": "#c9c7b9",
        outline: "#76777d",
        "surface-container-low": "#eff3ff",
        "sand-border": "#E4E2D4"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "max-width": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        sm: "8px",
        md: "16px",
        unit: "4px",
        lg: "24px",
        xl: "40px",
        gutter: "24px",
        "2xl": "64px",
        xs: "4px"
      },
      fontFamily: {
        body: ["var(--font-body)", "Inter", "sans-serif"],
        display: ["var(--font-display)", "Instrument Serif", "serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
